import { cn } from '@/lib/utils';
import './globals.css';
import { Inter } from 'next/font/google';
import Sidebar from '@/components/basic/Sidebar';
import Header from '@/components/basic/Header';
import Provider from './provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'antialiased text-slate-900')}>
        <Provider>
          <div className="bg-slate-100 min-h-screen">
            <Sidebar />
            <div className="ml-72">
              <Header />
            </div>
            <main className="p-6 mx-auto max-w-screen-2xl ml-72">
              <div className="p-4 bg-white rounded-md w-full">{children}</div>
            </main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
